# Generated by Django 2.1 on 2018-08-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SysSetting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='category_no',
            new_name='category',
        ),
    ]
