# Generated by Django 2.1 on 2018-08-26 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SysSetting', '0002_auto_20180825_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bom',
            old_name='Consume_coefficient_ab',
            new_name='consume_coefficient_ab',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='Consume_coefficient_sb',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='Consume_coefficient_sw',
        ),
        migrations.AddField(
            model_name='bom',
            name='consume_coefficient_sb',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=18, verbose_name='钢带消耗系数'),
        ),
        migrations.AddField(
            model_name='bom',
            name='consume_coefficient_sw',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=18, verbose_name='钢丝消耗系数'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='aluminum_band_no',
            field=models.ForeignKey(blank=True, limit_choices_to={'material_name__contains': '铝带'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ab_bom', to='SysSetting.Material', verbose_name='铝带型号'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='customer',
            field=models.CharField(choices=[('ZY', '自营'), ('DX', '电信'), ('YD', '移动'), ('LT', '联通')], max_length=30, verbose_name='客户类型'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='product_no',
            field=models.ForeignKey(limit_choices_to={'material_name__contains': '光缆'}, on_delete=django.db.models.deletion.CASCADE, related_name='pro_bom', to='SysSetting.Material', verbose_name='产品类型'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='steel_band_no',
            field=models.ForeignKey(blank=True, limit_choices_to={'material_name__contains': '钢带'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sb_bom', to='SysSetting.Material', verbose_name='钢带型号'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='steel_wire_no',
            field=models.ForeignKey(blank=True, limit_choices_to={'material_name__contains': '钢丝'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sw_bom', to='SysSetting.Material', verbose_name='钢丝型号'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_value',
            field=models.CharField(max_length=40, null=True, verbose_name='物料编码'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bom_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_order', to='SysSetting.BOM', verbose_name='BOM'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='订单编号'),
        ),
    ]
