# Generated by Django 2.1 on 2018-09-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SysSetting', '0002_auto_20180829_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectcode',
            name='object_value',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
