# Generated by Django 2.1 on 2018-08-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SysSetting', '0003_auto_20180826_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='aluminum_band_no',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='product_no',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='steel_band_no',
        ),
        migrations.RemoveField(
            model_name='bom',
            name='steel_wire_no',
        ),
        migrations.RemoveField(
            model_name='bomextend',
            name='basic_model_extend_no',
        ),
        migrations.RemoveField(
            model_name='bomextend',
            name='bom_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bom_no',
        ),
        migrations.DeleteModel(
            name='BOM',
        ),
        migrations.DeleteModel(
            name='BOMExtend',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
