# Generated by Django 2.1 on 2018-08-26 08:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SysSetting', '0004_auto_20180826_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('bom_no', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('customer', models.CharField(choices=[('ZY', '自营'), ('DX', '电信'), ('YD', '移动'), ('LT', '联通')], max_length=30, verbose_name='客户类型')),
                ('steel_wire_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='钢丝重量_kg')),
                ('consume_coefficient_sw', models.DecimalField(decimal_places=3, default=1.0, max_digits=18, verbose_name='钢丝消耗系数')),
                ('aluminum_band_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='铝带重量_kg')),
                ('consume_coefficient_ab', models.DecimalField(decimal_places=3, default=1.0, max_digits=18, verbose_name='铝带消耗系数')),
                ('steel_band_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='钢带重量_kg')),
                ('consume_coefficient_sb', models.DecimalField(decimal_places=3, default=1.0, max_digits=18, verbose_name='钢带消耗系数')),
                ('aluminum_band_width', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='铝带宽度_mm')),
                ('create_by', models.CharField(blank=True, max_length=30, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=30, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('del_flag', models.BooleanField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('aluminum_band_no', models.ForeignKey(blank=True, limit_choices_to={'material_name__contains': '铝带'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ab_bom', to='SysSetting.Material', verbose_name='铝带型号')),
                ('cable_structure', models.ForeignKey(limit_choices_to={'material_name__contains': '光缆结构'}, on_delete=django.db.models.deletion.CASCADE, related_name='cs_bom', to='SysSetting.Material', verbose_name='光缆结构')),
                ('product_no', models.ForeignKey(limit_choices_to={'material_name__contains': '光缆'}, on_delete=django.db.models.deletion.CASCADE, related_name='pro_bom', to='SysSetting.Material', verbose_name='产品类型')),
                ('steel_band_no', models.ForeignKey(blank=True, limit_choices_to={'material_name__contains': '钢带'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sb_bom', to='SysSetting.Material', verbose_name='钢带型号')),
                ('steel_wire_no', models.ForeignKey(blank=True, limit_choices_to={'material_name__contains': '钢丝'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sw_bom', to='SysSetting.Material', verbose_name='钢丝型号')),
            ],
        ),
        migrations.CreateModel(
            name='BOMExtend',
            fields=[
                ('bom_extend_no', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('bom_extend_value', models.CharField(max_length=30)),
                ('create_by', models.CharField(blank=True, max_length=30, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=30, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('del_flag', models.BooleanField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('basic_model_extend_no', models.ForeignKey(limit_choices_to={'model_extend_value__istartswith': 'BOM'}, on_delete=django.db.models.deletion.CASCADE, related_name='modelextend_bomextend', to='SysSetting.BasicModelExtend')),
                ('bom_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SysSetting.BOM')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_no', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('order_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='订单编号')),
                ('order_value', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='合同长度_km')),
                ('steel_wire_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='钢丝重量_kg')),
                ('aluminum_band_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='铝带重量_kg')),
                ('steel_band_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='钢带重量_kg')),
                ('aluminum_band_width', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='铝带宽度_mm')),
                ('create_by', models.CharField(blank=True, max_length=30, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=30, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('del_flag', models.BooleanField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('bom_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_order', to='SysSetting.BOM', verbose_name='BOM')),
            ],
        ),
    ]
