# Generated by Django 2.1 on 2018-08-30 03:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BomMan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('order_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='订单编号')),
                ('order_value', models.CharField(blank=True, max_length=30, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18, verbose_name='合同长度_km')),
                ('steel_wire_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='钢丝重量_kg')),
                ('aluminum_band_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='铝带重量_kg')),
                ('steel_band_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='钢带重量_kg')),
                ('aluminum_band_width', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True, verbose_name='铝带宽度_mm')),
                ('create_by', models.CharField(blank=True, max_length=30, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_by', models.CharField(blank=True, max_length=30, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('del_flag', models.BooleanField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=50, null=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_order', to='BomMan.BOM', verbose_name='BOM')),
            ],
            options={
                'verbose_name': '订单管理',
                'verbose_name_plural': '订单管理',
            },
        ),
    ]
